spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: public


security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1
    refresh: 30

api:
  key: DUEYl5LGY5Bn0jgAFYAnGcWX1DmBjoiQ
